
<?php
if ($message == "Well done! You have posted your anekdot! Very funny!") {
    ?> <h1 class="welcome-sign">Success</h1>
<?php
} else {
    ?> <h1 class="welcome-sign">Error</h1>
<?php
}
?>

<h2>
    <?php echo $message; ?>
</h2>

<?php if(! $success){?>
    <form action="/phalcon_crud/anekdot-post">
        <button type="submit" class="submit">Try again</button>
    </form>
<?php } ?>
<br>
<form action="/phalcon_crud">
    <button type="submit" class="submit">Go back and read some anekdots</button>
</form>

