

<h1>Change text of anekdot:</h1>

<?php

echo $this->tag->form(["action" => "../save", "method" => "post", "class" => "input", "name" => "Save"]);

echo $this->tag->inputText("Text", $anekdot->text, ["class" => "text"]); ?>
<p>
    <input type="hidden" name="anekdotId" value="<?php echo $anekdot->id ?>">
    <?php echo $this->tag->inputSubmit("SaveInput", "Save", ["class" => "submit"]); ?>
</p>
