<h2>Sign up using this form</h2>

<?php echo $this->tag->form(['action' => "signup/register", 'method' => 'post',
        'class'  => 'input', 'name' => 'Register']); ?>

    <p>
        <label for="name">Name</label>
        <?php echo $this->tag->inputText("name"); ?>
    </p>

    <p>
        <label for="email">E-Mail</label>
        <?php echo $this->tag->inputText("email"); ?>
    </p>

    <p>
        <?php echo $this->tag->inputSubmit('Register'); ?>
    </p>

</form>