<?php use Phalcon\Tag; ?>

<h1 class="welcome-sign">Welcome to FunnyAnekdots.ee!</h1>

<div class="link">
    <a href="/phalcon_crud/anekdot-post">Post your anekdot here!</a>
</div>

<hr>

<?php
if ($funny_count == 0) {
    ?>
    <h2>No anekdots is here....</h2>
    <?php
} else {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Anekdot number</th>
            <th>Author</th>
            <th>Anekdot</th>
            <th>Rating</th>
            <th colspan="3" class="table-button"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($anekdots as $anekdot) {
            if ($anekdot->status === "Active") {
            ?>
            <tr>
                <td><?php echo $anekdot->number; ?></td>
                <td><?php echo $anekdot->author; ?></td>
                <td><?php echo $anekdot->text; ?></td>
                <td><?php echo $anekdot->rating; ?></td>
                <td class="table-button">
                    <a href="index/ratingAdd/id=<?php echo $anekdot->id ?>" class="rating">👍</a>
                    <a href="index/ratingSubtract/id=<?php echo $anekdot->id ?>" class="rating">👎</a>
                </td>
                <td class="table-button">
                    <?php echo $this->tag->form(["action" => "index/delete", "method" => "post", "class" => "input", "name" => "Delete"]);

                        echo $this->tag->inputSubmit($anekdot->id, "delete");

                    echo Tag::endForm(); ?>
                </td>
                <td class="table-button">
                    <?php echo $this->tag->form(["action" => "change", "method" => "post", "class" => "input", "name" => "Change"]);

                    echo $this->tag->inputSubmit($anekdot->id, "✎");

                    echo Tag::endForm(); ?>
                </td>
            </tr>
            <?php
        }
        } ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4">Anekdots quantity: <?php echo $funny_count; ?></td>
            <td colspan="3" class="table-button"></td>
        </tr>
        </tfoot>
    </table>
    <?php
}
?>

<a href="/phalcon_crud/bin" class="bin link">🗑</a>
