<h1>Welcome to FunnyAnekdots.ee!</h1>

<a href="/phalcon-tutorial/anekdot-post">Post your anekdot here!</a>
<a href="/phalcon-tutorial/bin">Trash bin</a>

<?php
if ($anekdots->count() == 0) {
    ?>
    <h3>No anekdots is here....</h3>
    <?php
} else {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Anekdot number</th>
            <th>Author</th>
            <th>Anekdot</th>
            <th>Rating</th>
        </tr>
        </thead>
        <hr>
        <tbody>
        <?php foreach ($anekdots as $anekdot) { ?>
            <tr>
                <td><?php echo $anekdot->id; ?></td>
                <td><?php echo $anekdot->author; ?></td>
                <td><?php echo $anekdot->text; ?></td>
                <td><?php echo $anekdot->rating; ?></td>
                <td>
                    <?php echo $this->tag->form(["action" => "index/rating", "method" => "post", "class" => "input", "name" => "Rating"]) ?>
                    <p>
                        <?php echo $this->tag->inputSubmit($anekdot->id, "+"); ?>
                        <?php echo $this->tag->inputSubmit($anekdot->id, "-"); ?>
<!--                        <input type="hidden" name="Id" value="--><?php //echo $anekdot->id ?><!--">-->
                    </p>
                </td>
                <td>
                    <?php echo $this->tag->form(["action" => "index/delete", "method" => "post", "class" => "input", "name" => "Delete"]) ?>
                    <p>
<!--                        <input hidden name="Id" value="--><?php //echo $anekdot->id ?><!--">-->
                        <?php echo $this->tag->inputSubmit("Delete", "X"); ?>
                    </p>
                </td>
            </tr>
            <?php
        } ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="3">Anekdots quantity: <?php echo $anekdot->count(); ?></td>
        </tr>
        </tfoot>
    </table>
    <?php
}
?>
