
<h1 class="welcome-sign">Welcome to FunnyAnekdots.ee!</h1>

<div>
    <a href="/phalcon_crud/anekdot-post" class="link">Post your anekdot here!</a>
</div>

<hr>

<?php
$anekdot_number = 1;

if ($funny_count == 0) {
    ?>
    <h2>No anekdots is here....</h2>
    <?php
} else {
    ?>
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            <th>Anekdot number</th>
            <th>Author</th>
            <th>Anekdot</th>
            <th>Rating</th>
            <th colspan="3" class="table-button"></th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($anekdots as $anekdot) {
            if ($anekdot->status == "Active") {
            ?>
            <tr>
                <td><?php echo $anekdot_number; ?></td>
                <td><?php echo $anekdot->author; ?></td>
                <td><?php echo $anekdot->text; ?></td>
                <td><?php echo $anekdot->rating; ?></td>
                <td class="table-button">
                    <a href="index/ratingAdd/id=<?php echo $anekdot->id ?>" class="anekdot-action">👍</a>
                    <a href="index/ratingSubtract/id=<?php echo $anekdot->id ?>" class="anekdot-action">👎</a>
                </td>
                <td class="table-button">
                    <a href="index/delete/id=<?php echo $anekdot->id ?>" class="anekdot-action">Delete</a>
                </td>
                <td class="table-button">
                    <a href="change/index/id=<?php echo $anekdot->id ?>" class="anekdot-action">✎</a>
                </td>
            </tr>
            <?php
                $anekdot_number += 1;
            }
        } ?>
        </tbody>
        <tfoot>
        <tr>
            <td colspan="4">Anekdots quantity: <?php echo $funny_count; ?></td>
            <td colspan="3" class="table-button"></td>
        </tr>
        </tfoot>
    </table>
    <?php
}
?>

<a href="/phalcon_crud/bin" class="bin link">🗑</a>
